CREATE SEQUENCE seq_news;
CREATE TABLE news(
	id INT PRIMARY KEY DEFAULT NEXTVAL('seq_news'),
	title VARCHAR(255),
	body TEXT,
	published_at TIMESTAMP NOT NULL DEFAULT NOW(),
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
