#!/usr/bin/env bash

# Daily robots
#
# See README.md for more information.

cd $(dirname $0)
cd ..

./scripts/robot_runner sessions_cleanup
./scripts/robot_runner one_time_passwords_cleanup
./scripts/robot_runner invalid_password_attempts_cleanup
./scripts/robot_runner vacuum_analyze
